#!/bin/bash
feh --bg-scale /usr/bluemium/wallpaper.png &

KEYS_FILE="$HOME/.config/bluemium/oauth2.conf"

CHROME_ARGS=""
if [ -f "$KEYS_FILE" ]; then
  source "$KEYS_FILE"
  CHROME_ARGS="--login-manager \
    --oauth2-client-id=$OAUTH2_CLIENT_ID \
    --oauth2-client-secret=$OAUTH2_CLIENT_SECRET"
fi

(
  while ! wmctrl -l | grep -q .; do sleep 0.2; done
  wmctrl -r :ACTIVE: -b add,maximized_vert,maximized_horz
  wmctrl -r :ACTIVE: -b add,fullscreen
) &

/usr/bluemium/cros/chrome $CHROME_ARGS
# sends you back to the login screen just cause
openbox --exit
